import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header'
import GSAPAnimations from '@/components/utils/gsap-animations'
import type { Metadata } from "next"
import { Onest } from "next/font/google"
import "./globals.css"

const onest = Onest({
  variable: "--font-onest",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Smart Jobs",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${onest.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
        <GSAPAnimations />
      </body>
    </html>
  )
}
