import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header'
import GSAPAnimations from '@/components/utils/gsap-animations'
import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import { notFound } from 'next/navigation'
import '../../globals.css'

const onest = Onest({
  variable: '--font-onest',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Smart Jobs',
  description: 'Generated by create next app',
}

const locales = ['en', 'ro', 'ru']

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<'/[locale]'>) {
  const { locale } = await params

  if (!locales.includes(locale)) notFound()

  return (
    <html lang={locale} className={`${onest.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header locale={locale} />
        {children}
        <Footer locale={locale as 'en' | 'ro' | 'ru'} />
        <GSAPAnimations />
      </body>
    </html>
  )
}
